# Railway deployment configuration
[build]
  builder = "NIXPACKS"

[build.env]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.11"

[deploy]
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  PORT = 5000
  FLASK_ENV = "production"